"""making onwer_viewed column

Revision ID: 0a911f48a436
Revises: 2af778045fa9
Create Date: 2023-05-30 20:10:53.989422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a911f48a436'
down_revision = '2af778045fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visualizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_viewed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visualizations', schema=None) as batch_op:
        batch_op.drop_column('owner_viewed')

    # ### end Alembic commands ###
