"""EOD added chart_data col to vis

Revision ID: 3dd01f418f3b
Revises: 6dca546cf1b1
Create Date: 2023-05-26 01:12:28.884225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd01f418f3b'
down_revision = '6dca546cf1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visualizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chart_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visualizations', schema=None) as batch_op:
        batch_op.drop_column('chart_data')

    # ### end Alembic commands ###
