"""removed manual data from vis table

Revision ID: 6dca546cf1b1
Revises: f725402043ec
Create Date: 2023-05-23 18:28:41.993696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dca546cf1b1'
down_revision = 'f725402043ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visualizations', schema=None) as batch_op:
        batch_op.drop_column('manual_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visualizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_data', sa.VARCHAR(length=1000), nullable=True))

    # ### end Alembic commands ###
