""" updated ecsv enum val to text/csv

Revision ID: 9c08ce6c9e2d
Revises: 3dd01f418f3b
Create Date: 2023-05-26 22:54:01.986409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c08ce6c9e2d'
down_revision = '3dd01f418f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_files', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Enum('text/csv', 'json', 'xlsx', name='filetype_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_files', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=sa.Enum('text/csv', 'json', 'xlsx', name='filetype_enum'),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###
