"""changed enum col

Revision ID: a531f9918d95
Revises: f9c8aedf63f1
Create Date: 2023-06-01 21:42:59.584783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a531f9918d95'
down_revision = 'f9c8aedf63f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('visualization_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('data_files', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=65),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('visualization_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('visualizations', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visualizations', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('visualization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('data_files', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=65),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('visualization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
