""" updated seed and modal for other file types

Revision ID: f21aecdc5df8
Revises: 9c08ce6c9e2d
Create Date: 2023-05-26 23:28:37.455169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21aecdc5df8'
down_revision = '9c08ce6c9e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_files', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('text/csv', 'application/json', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', name='filetype_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_files', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=sa.Enum('text/csv', 'application/json', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', name='filetype_enum'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
